version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # Rest of the steps...

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build

