version: 2.1
jobs:
  build:
    docker:
      image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Create EC2 instance
          command: |
            terraform init
            terraform apply
