version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      # Install Terraform
      - run:
          name: Install Terraform
          command: |
            curl -LO https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
            unzip terraform_0.15.5_linux_amd64.zip
            sudo mv terraform /usr/local/bin/

      # Create .aws directory
      - run:
          name: Create .aws directory
          command: mkdir -p ~/.aws

      # Authenticate with AWS
      - run:
          name: Configure AWS credentials
          command: |
            echo -e "[default]\naws_access_key_id=$AWS_ACCESS_KEY_ID\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY" > ~/.aws/credentials
            echo -e "[default]\nregion=$AWS_DEFAULT_REGION" > ~/.aws/config

      # Initialize Terraform
      - run:
          name: Initialize Terraform
          command: terraform init

      # Validate Terraform configuration
      - run:
          name: Validate Terraform configuration
          command: terraform validate

      # Apply Terraform changes
      - run:
          name: Apply Terraform changes
          command: terraform apply -auto-approve

      # Set GitHub token environment variable
      - run:
          name: Set GitHub token environment variable
          command: echo "export GITHUB_TOKEN=$GITHUB_TOKEN" >> $BASH_ENV && source $BASH_ENV

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build

version: 2.1
jobs:
  build:
    docker:
      image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Create EC2 instance
          command: |
            terraform init
            terraform apply
